### ISSUE TITLE
Different behaviour than previous version

### ISSUE THREAD

**Issue by tarik81** [betsol/angular-input-modified#11]
http://plnkr.co/edit/KmVRcuwXYxEzNFseYI6y?p=preview

In latest version form is flagged modified, but if you comment script tag for latest version at the bottom in index.html and uncomment reference to version 1.2.0 then form is not flagged modified.

**Comment by slavafomin** [comment]
Hello @tarik81!

Thank you for your interest in this module and for your bug-report.

Starting from the version `2.0.0` the module is using a more robust way to initialize he master value of the `ngModel`. It is introduced in [this commit](https://github.com/betsol/angular-input-modified/commit/1317b85bf065171ceaa904bc37c79be692ac9768). You can see that the initialization flag is now used instead of the `typeof` comparison.

You can see it in the changelog:

*#8: "Doesn't work when bound object member isn't set" (thanks to Chris Yates). We are now using a more robust way to initialize master value (initialization flag).*

I'm sorry for the inconvinience it may caused you. However, it can be a backward-incompatible change, but it is introduced in the major update, so this is prefectly fine with the *SemVer* specification. I will update the changelog to outline this issue for other migrating users.

Thank you!

**Comment by slavafomin** [comment]
Considering your use case I will recommend to fetch the data in the resolve stage of your routing. The best approach is to always initialize the form data synchronously with the controller execution (i.e. without a delay).

If my answer solved your issue - please consider to close it. If you have any other questions - I will be glad to assist you. Cheers!

**Comment by slavafomin** [comment]
I've updated the Changelog and also added a section to the README on the topic of form initialization, please see it here: https://github.com/betsol/angular-input-modified/blob/master/readme.md#form-initialization.

**Comment by tarik81** [comment]
That solves my issue, thank you :)
