### ISSUE TITLE
Not working for dynamically added form fields

### ISSUE THREAD

**Issue by dhawalbhanushali** [betsol/angular-input-modified#12]
My application has a form where fields(select, input) are dynamically added. In this case "angular-input-modified" does not work as desired. Is there any workaround?

**Comment by dhawalbhanushali** [comment]
Sorry - It is working. My use case was a bit different.

**Comment by slavafomin** [comment]
Hello @dhawalbhanushali!

Thank you for your interest in this module.

We have an example where fields are created dynamically by `ngRepeat`, please review it: http://betsol.github.io/angular-input-modified/ng-repeat/.

Do you still have a problem? If so, please create a Plunk to demonstrate the issue. Otherwise - feel free to close this issue.

Thank you!

**Comment by dhawalbhanushali** [comment]
Issue solved. Thank you!
