### ISSUE TITLE
Radio buttons masterValue issue

### ISSUE THREAD

**Issue by turbosasa** [betsol/angular-input-modified#13]
There is a plunk
http://plnkr.co/edit/cu7KVY?p=preview

When set radio button masterValue from controller form is marked as modified. With simple text input fields masterValues works fine.

**Comment by rlamba89** [comment]
Please add another submit button for radio button.

Check this plunk.
http://plnkr.co/edit/LDZiwy

Hope this helps.

**Comment by slavafomin** [comment]
Hello @turbosasa, I can understand your confusion! To be honest, `masterValue` is a read-only property, you shouldn't set it directly (it's not watched). In order to change the master value you should set required value to the model and then call `$setPristine` on the input or form element.

I will try to update the docs soon, to make it more clear. Thank you for report.

If you have any further questions/issues — feel free to ask me anytime. Cheers!
