### ISSUE TITLE
[bug] Exception on resetting form when using nested using nested scopes

### ISSUE THREAD

**Issue by jrharshath** [betsol/angular-input-modified#35]
Here's a simplified version of the code that led me discover the bug:

```
<!-- html -->
<div ng-controller="MyCtrl as ctrl">
    <button ng-click="ctrl.resetForm()">Reset</button>
    <form name="myForm">
        <table>
            <tr ng-repeat="foo in ctrl.Foos">
                <td ng-repeat="bar in ctrl.Bars">
                    <input type="checkbox" ng-model="bar[foo.id]">
                </td>
            </tr>
        </table>
    </form>
</div>

// script
angular.module('app').controller('MyCtrl', function($scope) {
    ctrl.Foos = [ {id:'a'}, {id:'b'} ];
    ctrl.Bars = [ {a:true, b:false}, {a:false, b:true} ];

    this.resetForm = function ()
    {
        $scope.myForm.reset();
    }
})
```

On trying to reset the form from my controller, an exception gets thrown at `ngModel.js:156` (and subsequently ignored in line 159). The error is 

```
ReferenceError: foo is not defined
```

Any ideas for a bug fix?

**Comment by slavafomin** [comment]
Yep. I think it's a limitation of the module in the current implementation. You can see [here](https://github.com/betsol/angular-input-modified/blob/master/src/directive/ngModel.js#L30-L34) that `modelPath` variable is defined according to content of the `ngModel` attribute. Therefore, this attribute must contain a path to the model value relative to the current scope. You can't use nested references, because it's impossible to resolve them from the point of the scope.

If you would create a Plunk with your code I can try to help you with a workaround.

**Comment by slavafomin** [comment]
Hello @jrharshath! How are you doing?
I've updated the module to use more reliable `reset()` functionality.
Feel free to test your use case with it and tell me if it works for you!
Thanks!

**Comment by jrharshath** [comment]
Thanks! I'll test it out soon, and post results.

**Comment by slavafomin** [comment]
I'm closing this. Feel free to follow up if necessary.
